### ISSUE TITLE
Immersive Backroom Fabric 1.20.1 questions

### ISSUE THREAD

**Issue by Nate4Fate** [crafter312/fabric-backrooms-1.19.2#10]
First off, your backrooms mod is fantastic! My friends and I enjoyed it with the Immersive Portals mod!

Here are my questions. Is there a way to get out of the backrooms once you reach level 4? My friend and I have been looking in spectator mode and can't find a way back to the Overworld. I don't know if we missed something or not finding a specific structure or portal. I was using explorer's compass to see if there was a structure to get out for reference.

Another question is will there be entity(s) added later on? The noises in the backrooms are a nice touch and having something follow or come after us would be pretty intense. I loved the scary noise in level 2!

I don't want to rush you btw. These are my initial comments and questions :) I understand you're busy doing other things. Much love!

**Comment by crafter312** [comment]
Thank you so much for the response! I've been working on this for a while now with no real feedback from other people, so I'm glad to see that at least some other people have discovered it and given it a try.

As for your questions, there is currently not a way to get back to the overworld from level 4, since the elevator portal to get there is one way. My main goal at the moment is to implement the minimum number of levels required to make it back to the overworld if you explore for long enough. However, the last couple of dimensions are a little more complicated than the others I've added so far, so it might take me a little while longer to get to that point.

I would like to add entities eventually, since that is a big contributor to making the backrooms exciting and scary to explore. However, I've never added my own entity like that to the game before, so this is a bigger task I've kind of been avoiding 😅

I do plan on going back over all the dimensions and adding more details and things to explore eventually as well. I'm generally trying to use the backrooms wiki as reference, so any suggestions you may have in that line of things to add for exploration purposes would be welcome!

**Comment by crafter312** [comment]
As you alluded to, I am quite busy with other stuff, so adding all these things will take quite a while. At the very least, though, I'll try my best to keep the mod up-to-date with the latest version of Minecraft (of course depending on whether immersive portals and techreborn have been updated as well).
